### ISSUE TITLE
Update supported versions in clang-tools:all docker images

### ISSUE THREAD

**Issue by shenxianpeng** [shenxianpeng/clang-tools#20]
At this point `clang-tools:all` docker images support version includes 12 11 10 9 8 7 6.0.

Since there are 13, 14 releases, we should include 13, 14 while removing 7, 6.0 old releases to keep `clang-tools:all` from being too big(currently it is 1.2 GB).

This should not affect https://github.com/shenxianpeng/cpp-linter-action as few people use it yet, most people use the default version 10.

**Comment by 2bndy5** [comment]
Sounds good to me! 👍🏼
