### ISSUE TITLE
LLVM's clang license agreement

### ISSUE THREAD

**Issue by 2bndy5** [shenxianpeng/clang-tools#6]
I was just reading through [part 4](https://github.com/llvm/llvm-project/blob/c6457dcae88043cbd07dedc61b602b66b26f1ddf/clang/LICENSE.TXT#L93) of the [Apache License distributed with clang software](https://github.com/llvm/llvm-project/blob/main/clang/LICENSE.TXT). I think you need to include a copy of that License (you may keep your MIT License in addition) with this repo because you're (in a way) distributing clang software.

Maybe docker images are an exception to this (a copy of the License should already be in the built docker image), but it would probably be safer to do it anyway (there are stipulations about redistributing in either "source" or "object" forms).

**Comment by shenxianpeng** [comment]
You are right. I added LLVM clang license agreement via #7, could you help to check the change is good as you expect? thank you.
